project_id = "hwwpbtcgppzuscbvjkde"

[functions.cleanup-lesson-overrides]
verify_jwt = false

[functions.cleanup-trial-lessons]
verify_jwt = false

[functions.create-student]
verify_jwt = true

[functions.create-teacher]
verify_jwt = true

[functions.send-push]
verify_jwt = false

[functions.lesson-reminder-cron]
verify_jwt = false

[functions.notifications-push]
verify_jwt = false
