import type { WordEntry } from "./types";

/**
 * Fransızca kelime bankası — A1'den C2'ye, her seviyede 8 kelime.
 * Kart ön yüzünde kelime, arka yüzünde okunuş / anlam / örnek cümle bulunur.
 */
export const FR_WORDS: WordEntry[] = [
  // ------------------------------------------------------------------- A1
  {
    id: "fr-bonjour",
    word: "bonjour",
    pos: "phrase",
    level: "A1",
    category: "daily",
    phonetic: "/bɔ̃.ʒuʁ/",
    meaning: { tr: "merhaba, günaydın", en: "hello, good day", fr: "salutation du matin et de la journée" },
    example: "Bonjour, comment allez-vous ?",
    exampleT: { tr: "Merhaba, nasılsınız?", en: "Hello, how are you?" },
    synonyms: ["salut"],
    antonym: "au revoir",
  },
  {
    id: "fr-maison",
    word: "la maison",
    pos: "noun",
    level: "A1",
    category: "home",
    phonetic: "/mɛ.zɔ̃/",
    meaning: { tr: "ev", en: "house, home", fr: "bâtiment où l'on habite" },
    example: "Leur maison est près de l'école.",
    exampleT: { tr: "Evleri okulun yakınında.", en: "Their house is near the school." },
    synonyms: ["le logement"],
  },
  {
    id: "fr-eau",
    word: "l'eau",
    pos: "noun",
    level: "A1",
    category: "nature",
    phonetic: "/o/",
    meaning: { tr: "su", en: "water", fr: "liquide transparent que l'on boit" },
    example: "Je bois beaucoup d'eau en été.",
    exampleT: { tr: "Yazın çok su içerim.", en: "I drink a lot of water in summer." },
    synonyms: [],
  },
  {
    id: "fr-livre",
    word: "le livre",
    pos: "noun",
    level: "A1",
    category: "school",
    phonetic: "/livʁ/",
    meaning: { tr: "kitap", en: "book", fr: "ensemble de pages que l'on lit" },
    example: "Ce livre parle des animaux.",
    exampleT: { tr: "Bu kitap hayvanlarla ilgili.", en: "This book is about animals." },
    synonyms: ["l'ouvrage"],
  },
  {
    id: "fr-manger",
    word: "manger",
    pos: "verb",
    level: "A1",
    category: "food",
    phonetic: "/mɑ̃.ʒe/",
    meaning: { tr: "yemek yemek", en: "to eat", fr: "prendre de la nourriture" },
    example: "Nous mangeons à midi.",
    exampleT: { tr: "Öğlen yemek yeriz.", en: "We eat at noon." },
    synonyms: ["se nourrir"],
  },
  {
    id: "fr-ami",
    word: "l'ami",
    pos: "noun",
    level: "A1",
    category: "people",
    phonetic: "/a.mi/",
    meaning: { tr: "arkadaş", en: "friend", fr: "personne que l'on aime bien" },
    example: "Mon meilleur ami s'appelle Léo.",
    exampleT: { tr: "En yakın arkadaşımın adı Léo.", en: "My best friend is called Léo." },
    synonyms: ["le copain"],
    antonym: "l'ennemi",
  },
  {
    id: "fr-grand",
    word: "grand",
    pos: "adjective",
    level: "A1",
    category: "daily",
    phonetic: "/ɡʁɑ̃/",
    meaning: { tr: "büyük", en: "big, tall", fr: "de taille importante" },
    example: "C'est un grand jardin.",
    exampleT: { tr: "Bu büyük bir bahçe.", en: "It's a big garden." },
    synonyms: ["vaste"],
    antonym: "petit",
  },
  {
    id: "fr-chat",
    word: "le chat",
    pos: "noun",
    level: "A1",
    category: "nature",
    phonetic: "/ʃa/",
    meaning: { tr: "kedi", en: "cat", fr: "petit animal domestique" },
    example: "Le chat dort sur le canapé.",
    exampleT: { tr: "Kedi kanepede uyuyor.", en: "The cat is sleeping on the sofa." },
    synonyms: ["le félin"],
  },

  // ------------------------------------------------------------------- A2
  {
    id: "fr-chercher",
    word: "chercher",
    pos: "verb",
    level: "A2",
    category: "daily",
    phonetic: "/ʃɛʁ.ʃe/",
    meaning: { tr: "aramak", en: "to look for", fr: "essayer de trouver" },
    example: "Je cherche mes clés depuis ce matin.",
    exampleT: { tr: "Sabahtan beri anahtarlarımı arıyorum.", en: "I've been looking for my keys since this morning." },
    synonyms: ["rechercher"],
    antonym: "trouver",
  },
  {
    id: "fr-semaine",
    word: "la semaine",
    pos: "noun",
    level: "A2",
    category: "time",
    phonetic: "/sə.mɛn/",
    meaning: { tr: "hafta", en: "week", fr: "période de sept jours" },
    example: "Nous avons deux cours par semaine.",
    exampleT: { tr: "Haftada iki dersimiz var.", en: "We have two lessons a week." },
    synonyms: [],
  },
  {
    id: "fr-fatigue",
    word: "fatigué",
    pos: "adjective",
    level: "A2",
    category: "feelings",
    phonetic: "/fa.ti.ɡe/",
    meaning: { tr: "yorgun", en: "tired", fr: "qui a besoin de repos" },
    example: "Je suis fatigué après le travail.",
    exampleT: { tr: "İşten sonra yorgunum.", en: "I'm tired after work." },
    synonyms: ["épuisé", "las"],
    antonym: "reposé",
  },
  {
    id: "fr-cuisine",
    word: "la cuisine",
    pos: "noun",
    level: "A2",
    category: "home",
    phonetic: "/kɥi.zin/",
    meaning: { tr: "mutfak", en: "kitchen", fr: "pièce où l'on prépare les repas" },
    example: "Papa prépare le dîner dans la cuisine.",
    exampleT: { tr: "Babam mutfakta akşam yemeği hazırlıyor.", en: "Dad is making dinner in the kitchen." },
    synonyms: [],
  },
  {
    id: "fr-voisin",
    word: "le voisin",
    pos: "noun",
    level: "A2",
    category: "people",
    phonetic: "/vwa.zɛ̃/",
    meaning: { tr: "komşu", en: "neighbour", fr: "personne qui habite à côté" },
    example: "Notre voisin arrose les plantes.",
    exampleT: { tr: "Komşumuz bitkileri suluyor.", en: "Our neighbour waters the plants." },
    synonyms: [],
  },
  {
    id: "fr-arriver",
    word: "arriver",
    pos: "verb",
    level: "A2",
    category: "travel",
    phonetic: "/a.ʁi.ve/",
    meaning: { tr: "varmak", en: "to arrive", fr: "parvenir à un endroit" },
    example: "Le train arrive à six heures.",
    exampleT: { tr: "Tren altıda varıyor.", en: "The train arrives at six." },
    synonyms: ["parvenir"],
    antonym: "partir",
  },
  {
    id: "fr-tranquille",
    word: "tranquille",
    pos: "adjective",
    level: "A2",
    category: "daily",
    phonetic: "/tʁɑ̃.kil/",
    meaning: { tr: "sakin, sessiz", en: "quiet, calm", fr: "où il n'y a pas de bruit ni d'agitation" },
    example: "Le quartier est tranquille le dimanche.",
    exampleT: { tr: "Mahalle pazar günleri sakindir.", en: "The neighbourhood is quiet on Sundays." },
    synonyms: ["calme", "paisible"],
    antonym: "bruyant",
  },
  {
    id: "fr-marche",
    word: "le marché",
    pos: "noun",
    level: "A2",
    category: "food",
    phonetic: "/maʁ.ʃe/",
    meaning: { tr: "pazar, market", en: "market", fr: "lieu où l'on vend des produits" },
    example: "On achète les légumes au marché.",
    exampleT: { tr: "Sebzeleri pazardan alıyoruz.", en: "We buy vegetables at the market." },
    synonyms: [],
  },

  // ------------------------------------------------------------------- B1
  {
    id: "fr-reussir",
    word: "réussir",
    pos: "verb",
    level: "B1",
    category: "school",
    phonetic: "/ʁe.y.siʁ/",
    meaning: { tr: "başarmak", en: "to succeed", fr: "obtenir le résultat souhaité" },
    example: "Elle a réussi son examen d'anglais.",
    exampleT: { tr: "İngilizce sınavını başardı.", en: "She passed her English exam." },
    synonyms: ["parvenir", "aboutir"],
    antonym: "échouer",
  },
  {
    id: "fr-confiant",
    word: "confiant",
    pos: "adjective",
    level: "B1",
    category: "feelings",
    phonetic: "/kɔ̃.fjɑ̃/",
    meaning: { tr: "kendine güvenen", en: "confident", fr: "qui a confiance en soi" },
    example: "Il est plus confiant quand il parle anglais.",
    exampleT: { tr: "İngilizce konuşurken daha özgüvenli.", en: "He is more confident when he speaks English." },
    synonyms: ["sûr de soi"],
    antonym: "méfiant",
  },
  {
    id: "fr-occasion",
    word: "l'occasion",
    pos: "noun",
    level: "B1",
    category: "work",
    phonetic: "/ɔ.ka.zjɔ̃/",
    meaning: { tr: "fırsat", en: "opportunity", fr: "circonstance favorable" },
    example: "C'est une belle occasion d'apprendre.",
    exampleT: { tr: "Bu öğrenmek için güzel bir fırsat.", en: "It's a great opportunity to learn." },
    synonyms: ["la chance", "l'opportunité"],
  },
  {
    id: "fr-fiable",
    word: "fiable",
    pos: "adjective",
    level: "B1",
    category: "people",
    phonetic: "/fjabl/",
    meaning: { tr: "güvenilir", en: "reliable", fr: "à qui ou à quoi l'on peut se fier" },
    example: "C'est un collègue fiable.",
    exampleT: { tr: "Güvenilir bir iş arkadaşı.", en: "He is a reliable colleague." },
    synonyms: ["sûr", "digne de confiance"],
    antonym: "douteux",
  },
  {
    id: "fr-encourager",
    word: "encourager",
    pos: "verb",
    level: "B1",
    category: "school",
    phonetic: "/ɑ̃.ku.ʁa.ʒe/",
    meaning: { tr: "cesaretlendirmek", en: "to encourage", fr: "donner du courage à quelqu'un" },
    example: "Les professeurs encouragent les élèves à poser des questions.",
    exampleT: {
      tr: "Öğretmenler öğrencileri soru sormaya teşvik eder.",
      en: "Teachers encourage students to ask questions.",
    },
    synonyms: ["motiver", "soutenir"],
    antonym: "décourager",
  },
  {
    id: "fr-rendezvous",
    word: "le rendez-vous",
    pos: "noun",
    level: "B1",
    category: "time",
    phonetic: "/ʁɑ̃.de.vu/",
    meaning: { tr: "randevu", en: "appointment", fr: "rencontre fixée à l'avance" },
    example: "J'ai un rendez-vous à quatre heures.",
    exampleT: { tr: "Saat dörtte randevum var.", en: "I have an appointment at four." },
    synonyms: ["l'entrevue"],
  },
  {
    id: "fr-ameliorer",
    word: "améliorer",
    pos: "verb",
    level: "B1",
    category: "school",
    phonetic: "/a.me.ljɔ.ʁe/",
    meaning: { tr: "geliştirmek", en: "to improve", fr: "rendre meilleur" },
    example: "Lire chaque jour améliore le vocabulaire.",
    exampleT: { tr: "Her gün okumak kelime dağarcığını geliştirir.", en: "Reading every day improves vocabulary." },
    synonyms: ["perfectionner"],
    antonym: "détériorer",
  },
  {
    id: "fr-patient",
    word: "patient",
    pos: "adjective",
    level: "B1",
    category: "feelings",
    phonetic: "/pa.sjɑ̃/",
    meaning: { tr: "sabırlı", en: "patient", fr: "qui sait attendre sans s'énerver" },
    example: "Sois patient, les progrès prennent du temps.",
    exampleT: { tr: "Sabırlı ol, ilerleme zaman alır.", en: "Be patient, progress takes time." },
    synonyms: ["tolérant"],
    antonym: "impatient",
  },

  // ------------------------------------------------------------------- B2
  {
    id: "fr-reticent",
    word: "réticent",
    pos: "adjective",
    level: "B2",
    category: "feelings",
    phonetic: "/ʁe.ti.sɑ̃/",
    meaning: { tr: "isteksiz, çekingen", en: "reluctant", fr: "qui hésite à faire quelque chose" },
    example: "Elle était réticente à parler devant la classe.",
    exampleT: { tr: "Sınıfın önünde konuşmakta isteksizdi.", en: "She was reluctant to speak in front of the class." },
    synonyms: ["hésitant"],
    antonym: "enthousiaste",
  },
  {
    id: "fr-echeance",
    word: "l'échéance",
    pos: "noun",
    level: "B2",
    category: "work",
    phonetic: "/e.ʃe.ɑ̃s/",
    meaning: { tr: "son teslim tarihi", en: "deadline", fr: "date à laquelle quelque chose doit être fini" },
    example: "L'échéance du projet est lundi.",
    exampleT: { tr: "Projenin son teslim tarihi pazartesi.", en: "The project deadline is Monday." },
    synonyms: ["la date limite"],
  },
  {
    id: "fr-durable",
    word: "durable",
    pos: "adjective",
    level: "B2",
    category: "nature",
    phonetic: "/dy.ʁabl/",
    meaning: { tr: "sürdürülebilir, kalıcı", en: "sustainable, lasting", fr: "qui dure longtemps sans nuire" },
    example: "La ville investit dans les transports durables.",
    exampleT: { tr: "Şehir sürdürülebilir ulaşıma yatırım yapıyor.", en: "The city invests in sustainable transport." },
    synonyms: ["pérenne"],
    antonym: "éphémère",
  },
  {
    id: "fr-apercu",
    word: "l'aperçu",
    pos: "noun",
    level: "B2",
    category: "school",
    phonetic: "/a.pɛʁ.sy/",
    meaning: { tr: "genel bakış, fikir", en: "overview, insight", fr: "vue rapide et générale d'un sujet" },
    example: "Ce livre donne un bon aperçu de la méthode.",
    exampleT: { tr: "Bu kitap yöntem hakkında iyi bir fikir veriyor.", en: "This book gives a good overview of the method." },
    synonyms: ["le survol", "l'idée générale"],
  },
  {
    id: "fr-resilient",
    word: "résilient",
    pos: "adjective",
    level: "B2",
    category: "feelings",
    phonetic: "/ʁe.zi.ljɑ̃/",
    meaning: { tr: "dayanıklı, çabuk toparlanan", en: "resilient", fr: "capable de surmonter les épreuves" },
    example: "Les enfants sont étonnamment résilients.",
    exampleT: { tr: "Çocuklar şaşırtıcı derecede dayanıklıdır.", en: "Children are surprisingly resilient." },
    synonyms: ["robuste"],
    antonym: "fragile",
  },
  {
    id: "fr-negocier",
    word: "négocier",
    pos: "verb",
    level: "B2",
    category: "work",
    phonetic: "/ne.ɡɔ.sje/",
    meaning: { tr: "müzakere etmek", en: "to negotiate", fr: "discuter pour trouver un accord" },
    example: "Ils ont négocié un meilleur prix.",
    exampleT: { tr: "Daha iyi bir fiyat için pazarlık ettiler.", en: "They negotiated a better price." },
    synonyms: ["marchander"],
  },
  {
    id: "fr-reconnaissant",
    word: "reconnaissant",
    pos: "adjective",
    level: "B2",
    category: "feelings",
    phonetic: "/ʁə.kɔ.nɛ.sɑ̃/",
    meaning: { tr: "minnettar", en: "grateful", fr: "qui éprouve de la gratitude" },
    example: "Nous vous sommes reconnaissants de votre soutien.",
    exampleT: { tr: "Desteğiniz için minnettarız.", en: "We are grateful for your support." },
    synonyms: ["gré"],
    antonym: "ingrat",
  },
  {
    id: "fr-quotidien",
    word: "quotidien",
    pos: "adjective",
    level: "B2",
    category: "daily",
    phonetic: "/kɔ.ti.djɛ̃/",
    meaning: { tr: "günlük, her günkü", en: "daily, everyday", fr: "qui se produit chaque jour" },
    example: "La pratique quotidienne fait la différence.",
    exampleT: { tr: "Günlük pratik fark yaratır.", en: "Daily practice makes the difference." },
    synonyms: ["journalier"],
  },

  // ------------------------------------------------------------------- C1
  {
    id: "fr-meticuleux",
    word: "méticuleux",
    pos: "adjective",
    level: "C1",
    category: "work",
    phonetic: "/me.ti.ky.lø/",
    meaning: { tr: "titiz", en: "meticulous", fr: "qui soigne le moindre détail" },
    example: "Elle prend des notes méticuleuses après chaque cours.",
    exampleT: { tr: "Her dersten sonra titiz notlar tutuyor.", en: "She takes meticulous notes after every lesson." },
    synonyms: ["minutieux", "soigneux"],
    antonym: "négligent",
  },
  {
    id: "fr-soulager",
    word: "soulager",
    pos: "verb",
    level: "C1",
    category: "body",
    phonetic: "/su.la.ʒe/",
    meaning: { tr: "hafifletmek, rahatlatmak", en: "to relieve", fr: "diminuer une douleur ou une peine" },
    example: "Une courte pause peut soulager la pression.",
    exampleT: { tr: "Kısa bir mola baskıyı hafifletebilir.", en: "A short break can relieve the pressure." },
    synonyms: ["apaiser", "atténuer"],
    antonym: "aggraver",
  },
  {
    id: "fr-coherent",
    word: "cohérent",
    pos: "adjective",
    level: "C1",
    category: "school",
    phonetic: "/kɔ.e.ʁɑ̃/",
    meaning: { tr: "tutarlı", en: "coherent", fr: "dont les parties s'accordent logiquement" },
    example: "Construis un raisonnement cohérent.",
    exampleT: { tr: "Tutarlı bir akıl yürütme kur.", en: "Build a coherent line of reasoning." },
    synonyms: ["logique", "consistant"],
    antonym: "incohérent",
  },
  {
    id: "fr-discret",
    word: "discret",
    pos: "adjective",
    level: "C1",
    category: "people",
    phonetic: "/dis.kʁɛ/",
    meaning: { tr: "ağzı sıkı, ölçülü", en: "discreet", fr: "qui sait garder un secret, sans se faire remarquer" },
    example: "Il est resté discret sur la fête surprise.",
    exampleT: { tr: "Sürpriz parti konusunda ağzı sıkıydı.", en: "He stayed discreet about the surprise party." },
    synonyms: ["réservé"],
    antonym: "indiscret",
  },
  {
    id: "fr-inevitable",
    word: "inévitable",
    pos: "adjective",
    level: "C1",
    category: "time",
    phonetic: "/i.ne.vi.tabl/",
    meaning: { tr: "kaçınılmaz", en: "inevitable", fr: "que l'on ne peut pas éviter" },
    example: "Les erreurs sont une part inévitable de l'apprentissage.",
    exampleT: { tr: "Hatalar öğrenmenin kaçınılmaz bir parçasıdır.", en: "Mistakes are an inevitable part of learning." },
    synonyms: ["incontournable"],
    antonym: "évitable",
  },
  {
    id: "fr-repandu",
    word: "répandu",
    pos: "adjective",
    level: "C1",
    category: "people",
    phonetic: "/ʁe.pɑ̃.dy/",
    meaning: { tr: "yaygın", en: "widespread", fr: "que l'on rencontre très souvent" },
    example: "Cette erreur est répandue chez les débutants.",
    exampleT: { tr: "Bu hata yeni başlayanlar arasında yaygındır.", en: "This mistake is widespread among beginners." },
    synonyms: ["courant", "fréquent"],
    antonym: "rare",
  },
  {
    id: "fr-banal",
    word: "banal",
    pos: "adjective",
    level: "C1",
    category: "daily",
    phonetic: "/ba.nal/",
    meaning: { tr: "sıradan", en: "mundane, banal", fr: "sans originalité, très ordinaire" },
    example: "Même les tâches banales enseignent du vocabulaire.",
    exampleT: { tr: "Sıradan işler bile kelime öğretir.", en: "Even mundane tasks teach vocabulary." },
    synonyms: ["ordinaire", "commun"],
    antonym: "original",
  },
  {
    id: "fr-franc",
    word: "franc",
    pos: "adjective",
    level: "C1",
    category: "people",
    phonetic: "/fʁɑ̃/",
    meaning: { tr: "açık sözlü", en: "candid, frank", fr: "qui dit ce qu'il pense sans détour" },
    example: "Merci pour ton retour franc.",
    exampleT: { tr: "Açık sözlü geri bildirimin için teşekkürler.", en: "Thank you for your candid feedback." },
    synonyms: ["sincère", "direct"],
    antonym: "hypocrite",
  },

  // ------------------------------------------------------------------- C2
  {
    id: "fr-omnipresent",
    word: "omniprésent",
    pos: "adjective",
    level: "C2",
    category: "tech",
    phonetic: "/ɔm.ni.pʁe.zɑ̃/",
    meaning: { tr: "her yerde bulunan", en: "ubiquitous", fr: "présent partout à la fois" },
    example: "Les écrans sont omniprésents dans les salles de classe.",
    exampleT: { tr: "Ekranlar sınıflarda her yerde.", en: "Screens are ubiquitous in classrooms." },
    synonyms: ["ubiquitaire"],
    antonym: "rare",
  },
  {
    id: "fr-ephemere",
    word: "éphémère",
    pos: "adjective",
    level: "C2",
    category: "time",
    phonetic: "/e.fe.mɛʁ/",
    meaning: { tr: "kısa ömürlü, geçici", en: "ephemeral", fr: "qui ne dure que très peu de temps" },
    example: "La motivation est éphémère ; les habitudes durent.",
    exampleT: { tr: "Motivasyon geçicidir; alışkanlıklar kalıcıdır.", en: "Motivation is ephemeral; habits last." },
    synonyms: ["fugace", "passager"],
    antonym: "durable",
  },
  {
    id: "fr-laconique",
    word: "laconique",
    pos: "adjective",
    level: "C2",
    category: "people",
    phonetic: "/la.kɔ.nik/",
    meaning: { tr: "az ve öz konuşan", en: "laconic", fr: "qui s'exprime en très peu de mots" },
    example: "Sa réponse laconique ne nous a rien appris.",
    exampleT: { tr: "Kısacık cevabı bize hiçbir şey söylemedi.", en: "His laconic reply told us nothing." },
    synonyms: ["concis", "bref"],
    antonym: "verbeux",
  },
  {
    id: "fr-apparemment",
    word: "apparemment",
    pos: "adverb",
    level: "C2",
    category: "school",
    phonetic: "/a.pa.ʁa.mɑ̃/",
    meaning: { tr: "görünüşe göre", en: "apparently, ostensibly", fr: "selon ce qui semble être le cas" },
    example: "La réunion portait apparemment sur la planification.",
    exampleT: { tr: "Toplantı görünüşte planlamayla ilgiliydi.", en: "The meeting was apparently about scheduling." },
    synonyms: ["visiblement", "en apparence"],
  },
  {
    id: "fr-inexorable",
    word: "inexorable",
    pos: "adjective",
    level: "C2",
    category: "time",
    phonetic: "/i.nɛɡ.zɔ.ʁabl/",
    meaning: { tr: "önüne geçilemez", en: "inexorable", fr: "que rien ne peut arrêter" },
    example: "La marche inexorable de la technologie transforme l'enseignement.",
    exampleT: {
      tr: "Teknolojinin durdurulamaz ilerleyişi öğretimi dönüştürüyor.",
      en: "The inexorable march of technology transforms teaching.",
    },
    synonyms: ["implacable"],
  },
  {
    id: "fr-esoterique",
    word: "ésotérique",
    pos: "adjective",
    level: "C2",
    category: "school",
    phonetic: "/e.zɔ.te.ʁik/",
    meaning: { tr: "yalnızca uzmanların anladığı", en: "esoteric", fr: "compréhensible seulement par des initiés" },
    example: "Évitez le vocabulaire ésotérique avec des débutants.",
    exampleT: { tr: "Yeni başlayanlarla çok özel kelimelerden kaçının.", en: "Avoid esoteric vocabulary with beginners." },
    synonyms: ["obscur", "hermétique"],
    antonym: "accessible",
  },
  {
    id: "fr-loquace",
    word: "loquace",
    pos: "adjective",
    level: "C2",
    category: "people",
    phonetic: "/lɔ.kwas/",
    meaning: { tr: "geveze, konuşkan", en: "garrulous, talkative", fr: "qui parle beaucoup" },
    example: "Notre voisin loquace nous a retenus une heure.",
    exampleT: { tr: "Geveze komşumuz bizi bir saat tuttu.", en: "Our garrulous neighbour kept us for an hour." },
    synonyms: ["bavard", "volubile"],
    antonym: "taciturne",
  },
  {
    id: "fr-propension",
    word: "la propension",
    pos: "noun",
    level: "C2",
    category: "feelings",
    phonetic: "/pʁɔ.pɑ̃.sjɔ̃/",
    meaning: { tr: "eğilim", en: "propensity", fr: "tendance naturelle à agir d'une certaine façon" },
    example: "Il a une propension à trop réfléchir aux petites erreurs.",
    exampleT: {
      tr: "Küçük hataları fazla düşünme eğilimi var.",
      en: "He has a propensity to overthink small mistakes.",
    },
    synonyms: ["l'inclination", "le penchant"],
    antonym: "l'aversion",
  },
];
