import type { WordEntry } from "./types";

/**
 * İngilizce kelime bankası — A1'den C2'ye, her seviyede 12 kelime.
 * Günün kelimeleri buradan tarihe göre seçilir (bkz. `daily.ts`).
 */
export const EN_WORDS: WordEntry[] = [
  // ------------------------------------------------------------------- A1
  {
    id: "en-apple",
    word: "apple",
    pos: "noun",
    level: "A1",
    category: "food",
    phonetic: "/ˈæp.əl/",
    meaning: { tr: "elma", en: "a round fruit with red or green skin", fr: "pomme" },
    example: "I eat an apple every morning.",
    exampleT: { tr: "Her sabah bir elma yerim.", fr: "Je mange une pomme chaque matin." },
    synonyms: ["fruit"],
  },
  {
    id: "en-happy",
    word: "happy",
    pos: "adjective",
    level: "A1",
    category: "feelings",
    phonetic: "/ˈhæp.i/",
    meaning: { tr: "mutlu", en: "feeling pleased and cheerful", fr: "heureux" },
    example: "She looks very happy today.",
    exampleT: { tr: "Bugün çok mutlu görünüyor.", fr: "Elle a l'air très heureuse aujourd'hui." },
    synonyms: ["glad", "cheerful", "pleased"],
    antonym: "sad",
  },
  {
    id: "en-friend",
    word: "friend",
    pos: "noun",
    level: "A1",
    category: "people",
    phonetic: "/frend/",
    meaning: { tr: "arkadaş", en: "someone you like and know well", fr: "ami" },
    example: "My best friend lives next door.",
    exampleT: { tr: "En yakın arkadaşım yan kapıda oturuyor.", fr: "Mon meilleur ami habite à côté." },
    synonyms: ["mate", "buddy"],
    antonym: "enemy",
  },
  {
    id: "en-house",
    word: "house",
    pos: "noun",
    level: "A1",
    category: "home",
    phonetic: "/haʊs/",
    meaning: { tr: "ev", en: "a building where people live", fr: "maison" },
    example: "Their house has a small garden.",
    exampleT: { tr: "Evlerinin küçük bir bahçesi var.", fr: "Leur maison a un petit jardin." },
    synonyms: ["home"],
  },
  {
    id: "en-water",
    word: "water",
    pos: "noun",
    level: "A1",
    category: "nature",
    phonetic: "/ˈwɔː.tər/",
    meaning: { tr: "su", en: "the clear liquid we drink", fr: "eau" },
    example: "Please drink more water in summer.",
    exampleT: { tr: "Lütfen yazın daha çok su iç.", fr: "Buvez plus d'eau en été, s'il vous plaît." },
    synonyms: [],
  },
  {
    id: "en-book",
    word: "book",
    pos: "noun",
    level: "A1",
    category: "school",
    phonetic: "/bʊk/",
    meaning: { tr: "kitap", en: "printed pages held together to read", fr: "livre" },
    example: "This book is about animals.",
    exampleT: { tr: "Bu kitap hayvanlarla ilgili.", fr: "Ce livre parle des animaux." },
    synonyms: ["volume"],
  },
  {
    id: "en-run",
    word: "run",
    pos: "verb",
    level: "A1",
    category: "body",
    phonetic: "/rʌn/",
    meaning: { tr: "koşmak", en: "to move quickly on your feet", fr: "courir" },
    example: "We run in the park after school.",
    exampleT: { tr: "Okuldan sonra parkta koşarız.", fr: "Nous courons au parc après l'école." },
    synonyms: ["jog", "sprint"],
    antonym: "walk",
  },
  {
    id: "en-morning",
    word: "morning",
    pos: "noun",
    level: "A1",
    category: "time",
    phonetic: "/ˈmɔː.nɪŋ/",
    meaning: { tr: "sabah", en: "the early part of the day", fr: "matin" },
    example: "The lesson starts in the morning.",
    exampleT: { tr: "Ders sabah başlıyor.", fr: "Le cours commence le matin." },
    synonyms: [],
    antonym: "evening",
  },
  {
    id: "en-big",
    word: "big",
    pos: "adjective",
    level: "A1",
    category: "daily",
    phonetic: "/bɪɡ/",
    meaning: { tr: "büyük", en: "large in size", fr: "grand" },
    example: "That is a big dog!",
    exampleT: { tr: "Bu büyük bir köpek!", fr: "C'est un grand chien !" },
    synonyms: ["large", "huge"],
    antonym: "small",
  },
  {
    id: "en-family",
    word: "family",
    pos: "noun",
    level: "A1",
    category: "people",
    phonetic: "/ˈfæm.əl.i/",
    meaning: { tr: "aile", en: "parents, children and relatives", fr: "famille" },
    example: "My family has four people.",
    exampleT: { tr: "Ailem dört kişi.", fr: "Ma famille compte quatre personnes." },
    synonyms: ["household"],
  },
  {
    id: "en-teacher",
    word: "teacher",
    pos: "noun",
    level: "A1",
    category: "school",
    phonetic: "/ˈtiː.tʃər/",
    meaning: { tr: "öğretmen", en: "a person whose job is to teach", fr: "professeur" },
    example: "Our teacher is very kind.",
    exampleT: { tr: "Öğretmenimiz çok kibar.", fr: "Notre professeure est très gentille." },
    synonyms: ["tutor", "instructor"],
    antonym: "student",
  },
  {
    id: "en-cold",
    word: "cold",
    pos: "adjective",
    level: "A1",
    category: "nature",
    phonetic: "/kəʊld/",
    meaning: { tr: "soğuk", en: "having a low temperature", fr: "froid" },
    example: "It is cold outside, take your coat.",
    exampleT: { tr: "Dışarısı soğuk, montunu al.", fr: "Il fait froid dehors, prends ton manteau." },
    synonyms: ["chilly", "freezing"],
    antonym: "hot",
  },

  // ------------------------------------------------------------------- A2
  {
    id: "en-borrow",
    word: "borrow",
    pos: "verb",
    level: "A2",
    category: "daily",
    phonetic: "/ˈbɒr.əʊ/",
    meaning: { tr: "ödünç almak", en: "to take something and give it back later", fr: "emprunter" },
    example: "Can I borrow your pen for a minute?",
    exampleT: { tr: "Kalemini bir dakikalığına ödünç alabilir miyim?", fr: "Puis-je emprunter ton stylo une minute ?" },
    synonyms: ["take on loan"],
    antonym: "lend",
  },
  {
    id: "en-journey",
    word: "journey",
    pos: "noun",
    level: "A2",
    category: "travel",
    phonetic: "/ˈdʒɜː.ni/",
    meaning: { tr: "yolculuk", en: "an act of travelling from one place to another", fr: "voyage" },
    example: "The journey to the coast takes two hours.",
    exampleT: { tr: "Sahile yolculuk iki saat sürüyor.", fr: "Le voyage jusqu'à la côte dure deux heures." },
    synonyms: ["trip", "voyage"],
  },
  {
    id: "en-careful",
    word: "careful",
    pos: "adjective",
    level: "A2",
    category: "daily",
    phonetic: "/ˈkeə.fəl/",
    meaning: { tr: "dikkatli", en: "giving attention to avoid mistakes or danger", fr: "prudent" },
    example: "Be careful with the hot pan.",
    exampleT: { tr: "Sıcak tavaya dikkat et.", fr: "Fais attention à la poêle chaude." },
    synonyms: ["cautious", "attentive"],
    antonym: "careless",
  },
  {
    id: "en-kitchen",
    word: "kitchen",
    pos: "noun",
    level: "A2",
    category: "home",
    phonetic: "/ˈkɪtʃ.ɪn/",
    meaning: { tr: "mutfak", en: "the room where food is cooked", fr: "cuisine" },
    example: "Dad is cooking in the kitchen.",
    exampleT: { tr: "Babam mutfakta yemek yapıyor.", fr: "Papa cuisine dans la cuisine." },
    synonyms: [],
  },
  {
    id: "en-weather",
    word: "weather",
    pos: "noun",
    level: "A2",
    category: "nature",
    phonetic: "/ˈweð.ər/",
    meaning: { tr: "hava durumu", en: "the conditions of sun, rain, wind and temperature", fr: "météo" },
    example: "The weather is perfect for a picnic.",
    exampleT: { tr: "Hava piknik için harika.", fr: "La météo est parfaite pour un pique-nique." },
    synonyms: ["climate"],
  },
  {
    id: "en-decide",
    word: "decide",
    pos: "verb",
    level: "A2",
    category: "daily",
    phonetic: "/dɪˈsaɪd/",
    meaning: { tr: "karar vermek", en: "to choose after thinking", fr: "décider" },
    example: "We must decide before Friday.",
    exampleT: { tr: "Cumadan önce karar vermeliyiz.", fr: "Nous devons décider avant vendredi." },
    synonyms: ["choose", "determine"],
    antonym: "hesitate",
  },
  {
    id: "en-crowded",
    word: "crowded",
    pos: "adjective",
    level: "A2",
    category: "travel",
    phonetic: "/ˈkraʊ.dɪd/",
    meaning: { tr: "kalabalık", en: "full of people", fr: "bondé" },
    example: "The bus was crowded this morning.",
    exampleT: { tr: "Otobüs bu sabah kalabalıktı.", fr: "Le bus était bondé ce matin." },
    synonyms: ["packed", "busy"],
    antonym: "empty",
  },
  {
    id: "en-neighbour",
    word: "neighbour",
    pos: "noun",
    level: "A2",
    category: "people",
    phonetic: "/ˈneɪ.bər/",
    meaning: { tr: "komşu", en: "a person living next to you", fr: "voisin" },
    example: "Our neighbour looks after the cat.",
    exampleT: { tr: "Komşumuz kediye bakıyor.", fr: "Notre voisin s'occupe du chat." },
    synonyms: [],
  },
  {
    id: "en-arrive",
    word: "arrive",
    pos: "verb",
    level: "A2",
    category: "travel",
    phonetic: "/əˈraɪv/",
    meaning: { tr: "varmak", en: "to reach a place", fr: "arriver" },
    example: "The train arrives at six.",
    exampleT: { tr: "Tren altıda varıyor.", fr: "Le train arrive à six heures." },
    synonyms: ["reach", "get to"],
    antonym: "depart",
  },
  {
    id: "en-quiet",
    word: "quiet",
    pos: "adjective",
    level: "A2",
    category: "daily",
    phonetic: "/ˈkwaɪ.ət/",
    meaning: { tr: "sessiz", en: "making little or no noise", fr: "calme" },
    example: "The library is quiet in the afternoon.",
    exampleT: { tr: "Kütüphane öğleden sonra sessiz.", fr: "La bibliothèque est calme l'après-midi." },
    synonyms: ["silent", "peaceful"],
    antonym: "noisy",
  },
  {
    id: "en-healthy",
    word: "healthy",
    pos: "adjective",
    level: "A2",
    category: "body",
    phonetic: "/ˈhel.θi/",
    meaning: { tr: "sağlıklı", en: "well, or good for your health", fr: "sain" },
    example: "Vegetables are a healthy choice.",
    exampleT: { tr: "Sebzeler sağlıklı bir seçim.", fr: "Les légumes sont un choix sain." },
    synonyms: ["fit", "well"],
    antonym: "unhealthy",
  },
  {
    id: "en-hungry",
    word: "hungry",
    pos: "adjective",
    level: "A2",
    category: "food",
    phonetic: "/ˈhʌŋ.ɡri/",
    meaning: { tr: "aç", en: "wanting to eat", fr: "affamé" },
    example: "I get hungry after the lesson.",
    exampleT: { tr: "Dersten sonra acıkıyorum.", fr: "J'ai faim après le cours." },
    synonyms: ["starving", "peckish"],
    antonym: "full",
  },

  // ------------------------------------------------------------------- B1
  {
    id: "en-achieve",
    word: "achieve",
    pos: "verb",
    level: "B1",
    category: "school",
    phonetic: "/əˈtʃiːv/",
    meaning: { tr: "başarmak", en: "to succeed in doing something after effort", fr: "réaliser" },
    example: "She achieved her goal in six months.",
    exampleT: { tr: "Hedefini altı ayda başardı.", fr: "Elle a atteint son objectif en six mois." },
    synonyms: ["accomplish", "attain"],
    antonym: "fail",
  },
  {
    id: "en-confident",
    word: "confident",
    pos: "adjective",
    level: "B1",
    category: "feelings",
    phonetic: "/ˈkɒn.fɪ.dənt/",
    meaning: { tr: "özgüvenli", en: "sure of yourself and your abilities", fr: "confiant" },
    example: "He feels confident speaking English now.",
    exampleT: { tr: "Artık İngilizce konuşurken kendine güveniyor.", fr: "Il se sent confiant en parlant anglais." },
    synonyms: ["self-assured", "certain"],
    antonym: "insecure",
  },
  {
    id: "en-opportunity",
    word: "opportunity",
    pos: "noun",
    level: "B1",
    category: "work",
    phonetic: "/ˌɒp.əˈtʃuː.nə.ti/",
    meaning: { tr: "fırsat", en: "a chance to do something good", fr: "occasion" },
    example: "This job is a great opportunity for her.",
    exampleT: { tr: "Bu iş onun için harika bir fırsat.", fr: "Cet emploi est une belle occasion pour elle." },
    synonyms: ["chance", "opening"],
  },
  {
    id: "en-reliable",
    word: "reliable",
    pos: "adjective",
    level: "B1",
    category: "people",
    phonetic: "/rɪˈlaɪ.ə.bəl/",
    meaning: { tr: "güvenilir", en: "that you can trust or depend on", fr: "fiable" },
    example: "He is a reliable member of the team.",
    exampleT: { tr: "Ekibin güvenilir bir üyesi.", fr: "C'est un membre fiable de l'équipe." },
    synonyms: ["dependable", "trustworthy"],
    antonym: "unreliable",
  },
  {
    id: "en-exhausted",
    word: "exhausted",
    pos: "adjective",
    level: "B1",
    category: "feelings",
    phonetic: "/ɪɡˈzɔː.stɪd/",
    meaning: { tr: "bitkin", en: "extremely tired", fr: "épuisé" },
    example: "After the trip we were completely exhausted.",
    exampleT: { tr: "Yolculuktan sonra tamamen bitkindik.", fr: "Après le voyage, nous étions complètement épuisés." },
    synonyms: ["worn out", "drained"],
    antonym: "energetic",
  },
  {
    id: "en-encourage",
    word: "encourage",
    pos: "verb",
    level: "B1",
    category: "school",
    phonetic: "/ɪnˈkʌr.ɪdʒ/",
    meaning: { tr: "cesaretlendirmek", en: "to give someone confidence to do something", fr: "encourager" },
    example: "Good teachers encourage students to ask questions.",
    exampleT: {
      tr: "İyi öğretmenler öğrencileri soru sormaya teşvik eder.",
      fr: "Les bons professeurs encouragent les élèves à poser des questions.",
    },
    synonyms: ["motivate", "inspire"],
    antonym: "discourage",
  },
  {
    id: "en-appointment",
    word: "appointment",
    pos: "noun",
    level: "B1",
    category: "time",
    phonetic: "/əˈpɔɪnt.mənt/",
    meaning: { tr: "randevu", en: "an arranged meeting at a fixed time", fr: "rendez-vous" },
    example: "I have an appointment at four o'clock.",
    exampleT: { tr: "Saat dörtte randevum var.", fr: "J'ai un rendez-vous à quatre heures." },
    synonyms: ["meeting", "booking"],
  },
  {
    id: "en-generous",
    word: "generous",
    pos: "adjective",
    level: "B1",
    category: "people",
    phonetic: "/ˈdʒen.ər.əs/",
    meaning: { tr: "cömert", en: "willing to give money, help or time", fr: "généreux" },
    example: "It was generous of you to help.",
    exampleT: { tr: "Yardım etmen çok cömertti.", fr: "C'était généreux de ta part d'aider." },
    synonyms: ["giving", "kind"],
    antonym: "stingy",
  },
  {
    id: "en-improve",
    word: "improve",
    pos: "verb",
    level: "B1",
    category: "school",
    phonetic: "/ɪmˈpruːv/",
    meaning: { tr: "geliştirmek", en: "to become or make better", fr: "améliorer" },
    example: "Reading every day improves your vocabulary.",
    exampleT: {
      tr: "Her gün okumak kelime dağarcığını geliştirir.",
      fr: "Lire chaque jour améliore votre vocabulaire.",
    },
    synonyms: ["enhance", "develop"],
    antonym: "worsen",
  },
  {
    id: "en-patient",
    word: "patient",
    pos: "adjective",
    level: "B1",
    category: "feelings",
    phonetic: "/ˈpeɪ.ʃənt/",
    meaning: { tr: "sabırlı", en: "able to wait calmly", fr: "patient" },
    example: "Be patient — progress takes time.",
    exampleT: { tr: "Sabırlı ol — ilerleme zaman alır.", fr: "Sois patient : les progrès prennent du temps." },
    synonyms: ["tolerant", "calm"],
    antonym: "impatient",
  },
  {
    id: "en-budget",
    word: "budget",
    pos: "noun",
    level: "B1",
    category: "work",
    phonetic: "/ˈbʌdʒ.ɪt/",
    meaning: { tr: "bütçe", en: "a plan for how money will be spent", fr: "budget" },
    example: "The trip fits our budget.",
    exampleT: { tr: "Gezi bütçemize uyuyor.", fr: "Le voyage rentre dans notre budget." },
    synonyms: ["funds", "allowance"],
  },
  {
    id: "en-curious",
    word: "curious",
    pos: "adjective",
    level: "B1",
    category: "feelings",
    phonetic: "/ˈkjʊə.ri.əs/",
    meaning: { tr: "meraklı", en: "wanting to know or learn something", fr: "curieux" },
    example: "Children are naturally curious about everything.",
    exampleT: {
      tr: "Çocuklar doğal olarak her şeye meraklıdır.",
      fr: "Les enfants sont naturellement curieux de tout.",
    },
    synonyms: ["inquisitive", "interested"],
    antonym: "indifferent",
  },

  // ------------------------------------------------------------------- B2
  {
    id: "en-reluctant",
    word: "reluctant",
    pos: "adjective",
    level: "B2",
    category: "feelings",
    phonetic: "/rɪˈlʌk.tənt/",
    meaning: { tr: "isteksiz", en: "not willing to do something", fr: "réticent" },
    example: "She was reluctant to speak in front of the class.",
    exampleT: {
      tr: "Sınıfın önünde konuşmakta isteksizdi.",
      fr: "Elle était réticente à parler devant la classe.",
    },
    synonyms: ["unwilling", "hesitant"],
    antonym: "eager",
  },
  {
    id: "en-thorough",
    word: "thorough",
    pos: "adjective",
    level: "B2",
    category: "work",
    phonetic: "/ˈθʌr.ə/",
    meaning: { tr: "titiz, kapsamlı", en: "complete, with attention to every detail", fr: "minutieux" },
    example: "They did a thorough review of the report.",
    exampleT: { tr: "Raporu kapsamlı biçimde gözden geçirdiler.", fr: "Ils ont fait une revue minutieuse du rapport." },
    synonyms: ["comprehensive", "meticulous"],
    antonym: "superficial",
  },
  {
    id: "en-overwhelm",
    word: "overwhelm",
    pos: "verb",
    level: "B2",
    category: "feelings",
    phonetic: "/ˌəʊ.vəˈwelm/",
    meaning: { tr: "boğmak, altında bırakmak", en: "to affect someone so strongly they cannot cope", fr: "submerger" },
    example: "Too much homework can overwhelm a young learner.",
    exampleT: {
      tr: "Çok fazla ödev genç bir öğrenciyi bunaltabilir.",
      fr: "Trop de devoirs peut submerger un jeune apprenant.",
    },
    synonyms: ["swamp", "engulf"],
  },
  {
    id: "en-deadline",
    word: "deadline",
    pos: "noun",
    level: "B2",
    category: "work",
    phonetic: "/ˈded.laɪn/",
    meaning: { tr: "son teslim tarihi", en: "the latest time something must be finished", fr: "date limite" },
    example: "The deadline for the project is Monday.",
    exampleT: { tr: "Projenin son teslim tarihi pazartesi.", fr: "La date limite du projet est lundi." },
    synonyms: ["due date", "cut-off"],
  },
  {
    id: "en-sustainable",
    word: "sustainable",
    pos: "adjective",
    level: "B2",
    category: "nature",
    phonetic: "/səˈsteɪ.nə.bəl/",
    meaning: { tr: "sürdürülebilir", en: "able to continue without harming the environment", fr: "durable" },
    example: "The city is investing in sustainable transport.",
    exampleT: {
      tr: "Şehir sürdürülebilir ulaşıma yatırım yapıyor.",
      fr: "La ville investit dans les transports durables.",
    },
    synonyms: ["viable", "green"],
  },
  {
    id: "en-vivid",
    word: "vivid",
    pos: "adjective",
    level: "B2",
    category: "daily",
    phonetic: "/ˈvɪv.ɪd/",
    meaning: { tr: "canlı, çarpıcı", en: "producing very clear and strong images", fr: "vif" },
    example: "He gave a vivid description of the island.",
    exampleT: { tr: "Adayı çok canlı biçimde anlattı.", fr: "Il a donné une description vive de l'île." },
    synonyms: ["striking", "graphic"],
    antonym: "vague",
  },
  {
    id: "en-insight",
    word: "insight",
    pos: "noun",
    level: "B2",
    category: "school",
    phonetic: "/ˈɪn.saɪt/",
    meaning: { tr: "içgörü", en: "a clear, deep understanding of something", fr: "aperçu" },
    example: "The book offers real insight into how children learn.",
    exampleT: {
      tr: "Kitap, çocukların nasıl öğrendiğine dair gerçek bir içgörü sunuyor.",
      fr: "Le livre offre un véritable aperçu de l'apprentissage des enfants.",
    },
    synonyms: ["understanding", "perception"],
  },
  {
    id: "en-resilient",
    word: "resilient",
    pos: "adjective",
    level: "B2",
    category: "feelings",
    phonetic: "/rɪˈzɪl.i.ənt/",
    meaning: { tr: "dayanıklı, çabuk toparlanan", en: "able to recover quickly from difficulty", fr: "résilient" },
    example: "Children are surprisingly resilient.",
    exampleT: { tr: "Çocuklar şaşırtıcı derecede dayanıklıdır.", fr: "Les enfants sont étonnamment résilients." },
    synonyms: ["tough", "adaptable"],
    antonym: "fragile",
  },
  {
    id: "en-negotiate",
    word: "negotiate",
    pos: "verb",
    level: "B2",
    category: "work",
    phonetic: "/nəˈɡəʊ.ʃi.eɪt/",
    meaning: { tr: "müzakere etmek", en: "to discuss in order to reach an agreement", fr: "négocier" },
    example: "They negotiated a better price.",
    exampleT: { tr: "Daha iyi bir fiyat için pazarlık ettiler.", fr: "Ils ont négocié un meilleur prix." },
    synonyms: ["bargain", "discuss"],
  },
  {
    id: "en-ambiguous",
    word: "ambiguous",
    pos: "adjective",
    level: "B2",
    category: "school",
    phonetic: "/æmˈbɪɡ.ju.əs/",
    meaning: { tr: "belirsiz, iki anlamlı", en: "having more than one possible meaning", fr: "ambigu" },
    example: "The instructions were ambiguous, so we asked again.",
    exampleT: {
      tr: "Yönergeler belirsizdi, bu yüzden tekrar sorduk.",
      fr: "Les consignes étaient ambiguës, alors nous avons redemandé.",
    },
    synonyms: ["unclear", "vague"],
    antonym: "unambiguous",
  },
  {
    id: "en-tedious",
    word: "tedious",
    pos: "adjective",
    level: "B2",
    category: "work",
    phonetic: "/ˈtiː.di.əs/",
    meaning: { tr: "sıkıcı, yorucu", en: "boring because it lasts too long", fr: "fastidieux" },
    example: "Copying the list by hand was tedious.",
    exampleT: { tr: "Listeyi elle kopyalamak sıkıcıydı.", fr: "Recopier la liste à la main était fastidieux." },
    synonyms: ["dull", "monotonous"],
    antonym: "engaging",
  },
  {
    id: "en-grateful",
    word: "grateful",
    pos: "adjective",
    level: "B2",
    category: "feelings",
    phonetic: "/ˈɡreɪt.fəl/",
    meaning: { tr: "minnettar", en: "feeling thankful for something", fr: "reconnaissant" },
    example: "We are grateful for your support.",
    exampleT: { tr: "Desteğiniz için minnettarız.", fr: "Nous vous sommes reconnaissants de votre soutien." },
    synonyms: ["thankful", "appreciative"],
    antonym: "ungrateful",
  },

  // ------------------------------------------------------------------- C1
  {
    id: "en-meticulous",
    word: "meticulous",
    pos: "adjective",
    level: "C1",
    category: "work",
    phonetic: "/məˈtɪk.jə.ləs/",
    meaning: { tr: "titiz", en: "showing great attention to detail", fr: "méticuleux" },
    example: "She keeps meticulous notes after every lesson.",
    exampleT: {
      tr: "Her dersten sonra titiz notlar tutuyor.",
      fr: "Elle tient des notes méticuleuses après chaque cours.",
    },
    synonyms: ["scrupulous", "painstaking"],
    antonym: "careless",
  },
  {
    id: "en-alleviate",
    word: "alleviate",
    pos: "verb",
    level: "C1",
    category: "body",
    phonetic: "/əˈliː.vi.eɪt/",
    meaning: { tr: "hafifletmek", en: "to make pain or a problem less severe", fr: "soulager" },
    example: "A short break can alleviate the pressure.",
    exampleT: { tr: "Kısa bir mola baskıyı hafifletebilir.", fr: "Une courte pause peut soulager la pression." },
    synonyms: ["ease", "relieve"],
    antonym: "aggravate",
  },
  {
    id: "en-coherent",
    word: "coherent",
    pos: "adjective",
    level: "C1",
    category: "school",
    phonetic: "/kəʊˈhɪə.rənt/",
    meaning: { tr: "tutarlı", en: "logical and clearly connected", fr: "cohérent" },
    example: "Try to build a coherent argument in your essay.",
    exampleT: {
      tr: "Denemende tutarlı bir argüman kurmaya çalış.",
      fr: "Essayez de construire un argument cohérent dans votre essai.",
    },
    synonyms: ["logical", "consistent"],
    antonym: "incoherent",
  },
  {
    id: "en-discreet",
    word: "discreet",
    pos: "adjective",
    level: "C1",
    category: "people",
    phonetic: "/dɪˈskriːt/",
    meaning: { tr: "ağzı sıkı, ölçülü", en: "careful not to attract attention or reveal secrets", fr: "discret" },
    example: "He was discreet about the surprise party.",
    exampleT: { tr: "Sürpriz parti konusunda ağzı sıkıydı.", fr: "Il est resté discret sur la fête surprise." },
    synonyms: ["tactful", "prudent"],
    antonym: "indiscreet",
  },
  {
    id: "en-inevitable",
    word: "inevitable",
    pos: "adjective",
    level: "C1",
    category: "time",
    phonetic: "/ɪˈnev.ɪ.tə.bəl/",
    meaning: { tr: "kaçınılmaz", en: "certain to happen and impossible to avoid", fr: "inévitable" },
    example: "Mistakes are an inevitable part of learning.",
    exampleT: {
      tr: "Hatalar öğrenmenin kaçınılmaz bir parçasıdır.",
      fr: "Les erreurs sont une part inévitable de l'apprentissage.",
    },
    synonyms: ["unavoidable", "certain"],
    antonym: "avoidable",
  },
  {
    id: "en-prevalent",
    word: "prevalent",
    pos: "adjective",
    level: "C1",
    category: "people",
    phonetic: "/ˈprev.əl.ənt/",
    meaning: { tr: "yaygın", en: "common in a particular place or time", fr: "répandu" },
    example: "This mistake is prevalent among beginners.",
    exampleT: {
      tr: "Bu hata yeni başlayanlar arasında yaygındır.",
      fr: "Cette erreur est répandue chez les débutants.",
    },
    synonyms: ["widespread", "common"],
    antonym: "rare",
  },
  {
    id: "en-scrutinise",
    word: "scrutinise",
    pos: "verb",
    level: "C1",
    category: "work",
    phonetic: "/ˈskruː.tɪ.naɪz/",
    meaning: { tr: "didik didik incelemek", en: "to examine something very carefully", fr: "scruter" },
    example: "The editor scrutinised every sentence.",
    exampleT: { tr: "Editör her cümleyi didik didik inceledi.", fr: "L'éditeur a scruté chaque phrase." },
    synonyms: ["examine", "inspect"],
    antonym: "skim",
  },
  {
    id: "en-mundane",
    word: "mundane",
    pos: "adjective",
    level: "C1",
    category: "daily",
    phonetic: "/mʌnˈdeɪn/",
    meaning: { tr: "sıradan", en: "ordinary and not interesting", fr: "banal" },
    example: "Even mundane tasks can teach new vocabulary.",
    exampleT: {
      tr: "Sıradan işler bile yeni kelimeler öğretebilir.",
      fr: "Même les tâches banales peuvent enseigner du vocabulaire.",
    },
    synonyms: ["ordinary", "banal"],
    antonym: "extraordinary",
  },
  {
    id: "en-compelling",
    word: "compelling",
    pos: "adjective",
    level: "C1",
    category: "school",
    phonetic: "/kəmˈpel.ɪŋ/",
    meaning: { tr: "çarpıcı, ikna edici", en: "so interesting or convincing you must pay attention", fr: "convaincant" },
    example: "She made a compelling case for more speaking practice.",
    exampleT: {
      tr: "Daha çok konuşma pratiği için ikna edici bir gerekçe sundu.",
      fr: "Elle a présenté un argument convaincant pour plus de pratique orale.",
    },
    synonyms: ["persuasive", "gripping"],
    antonym: "unconvincing",
  },
  {
    id: "en-adept",
    word: "adept",
    pos: "adjective",
    level: "C1",
    category: "work",
    phonetic: "/əˈdept/",
    meaning: { tr: "usta, becerikli", en: "very skilled at something", fr: "habile" },
    example: "He is adept at explaining grammar simply.",
    exampleT: {
      tr: "Dil bilgisini basitçe anlatmakta ustadır.",
      fr: "Il est habile pour expliquer la grammaire simplement.",
    },
    synonyms: ["skilled", "proficient"],
    antonym: "inept",
  },
  {
    id: "en-candid",
    word: "candid",
    pos: "adjective",
    level: "C1",
    category: "people",
    phonetic: "/ˈkæn.dɪd/",
    meaning: { tr: "açık sözlü", en: "honest and direct, even when it is awkward", fr: "franc" },
    example: "Thank you for your candid feedback.",
    exampleT: { tr: "Açık sözlü geri bildiriminiz için teşekkürler.", fr: "Merci pour votre retour franc." },
    synonyms: ["frank", "straightforward"],
    antonym: "evasive",
  },
  {
    id: "en-nuance",
    word: "nuance",
    pos: "noun",
    level: "C1",
    category: "school",
    phonetic: "/ˈnjuː.ɑːns/",
    meaning: { tr: "ince ayrım, nüans", en: "a very small difference in meaning or tone", fr: "nuance" },
    example: "Advanced learners notice the nuance between the two words.",
    exampleT: {
      tr: "İleri seviye öğrenciler iki kelime arasındaki nüansı fark eder.",
      fr: "Les apprenants avancés remarquent la nuance entre les deux mots.",
    },
    synonyms: ["subtlety", "shade"],
  },

  // ------------------------------------------------------------------- C2
  {
    id: "en-ubiquitous",
    word: "ubiquitous",
    pos: "adjective",
    level: "C2",
    category: "tech",
    phonetic: "/juːˈbɪk.wɪ.təs/",
    meaning: { tr: "her yerde bulunan", en: "seeming to be everywhere at once", fr: "omniprésent" },
    example: "Smartphones have become ubiquitous in classrooms.",
    exampleT: {
      tr: "Akıllı telefonlar sınıflarda her yerde karşımıza çıkar oldu.",
      fr: "Les smartphones sont devenus omniprésents dans les salles de classe.",
    },
    synonyms: ["omnipresent", "pervasive"],
    antonym: "scarce",
  },
  {
    id: "en-perfunctory",
    word: "perfunctory",
    pos: "adjective",
    level: "C2",
    category: "work",
    phonetic: "/pəˈfʌŋk.tər.i/",
    meaning: { tr: "gelişigüzel, baştan savma", en: "done without care, just to get it over with", fr: "expéditif" },
    example: "He gave a perfunctory nod and left.",
    exampleT: { tr: "Baştan savma bir baş sallayıp gitti.", fr: "Il a hoché la tête de façon expéditive et est parti." },
    synonyms: ["cursory", "half-hearted"],
    antonym: "thorough",
  },
  {
    id: "en-quintessential",
    word: "quintessential",
    pos: "adjective",
    level: "C2",
    category: "people",
    phonetic: "/ˌkwɪn.tɪˈsen.ʃəl/",
    meaning: { tr: "en tipik, özünü taşıyan", en: "being the most perfect example of something", fr: "quintessentiel" },
    example: "She is the quintessential patient teacher.",
    exampleT: {
      tr: "Sabırlı öğretmenin en tipik örneğidir.",
      fr: "Elle est l'exemple même de l'enseignante patiente.",
    },
    synonyms: ["archetypal", "definitive"],
  },
  {
    id: "en-ephemeral",
    word: "ephemeral",
    pos: "adjective",
    level: "C2",
    category: "time",
    phonetic: "/ɪˈfem.ər.əl/",
    meaning: { tr: "kısa ömürlü, geçici", en: "lasting for a very short time", fr: "éphémère" },
    example: "Motivation is ephemeral; habits last.",
    exampleT: { tr: "Motivasyon geçicidir; alışkanlıklar kalıcıdır.", fr: "La motivation est éphémère ; les habitudes durent." },
    synonyms: ["fleeting", "transient"],
    antonym: "enduring",
  },
  {
    id: "en-laconic",
    word: "laconic",
    pos: "adjective",
    level: "C2",
    category: "people",
    phonetic: "/ləˈkɒn.ɪk/",
    meaning: { tr: "az ve öz konuşan", en: "using very few words", fr: "laconique" },
    example: "His laconic reply told us nothing.",
    exampleT: { tr: "Kısacık cevabı bize hiçbir şey söylemedi.", fr: "Sa réponse laconique ne nous a rien appris." },
    synonyms: ["terse", "concise"],
    antonym: "verbose",
  },
  {
    id: "en-ostensibly",
    word: "ostensibly",
    pos: "adverb",
    level: "C2",
    category: "school",
    phonetic: "/ɒsˈten.sə.bli/",
    meaning: { tr: "görünüşte", en: "as it appears, though perhaps not truly", fr: "apparemment" },
    example: "The meeting was ostensibly about scheduling.",
    exampleT: {
      tr: "Toplantı görünüşte planlamayla ilgiliydi.",
      fr: "La réunion portait apparemment sur la planification.",
    },
    synonyms: ["apparently", "supposedly"],
  },
  {
    id: "en-inexorable",
    word: "inexorable",
    pos: "adjective",
    level: "C2",
    category: "time",
    phonetic: "/ɪˈnek.sər.ə.bəl/",
    meaning: { tr: "önüne geçilemez", en: "impossible to stop or change", fr: "inexorable" },
    example: "The inexorable march of technology reshapes teaching.",
    exampleT: {
      tr: "Teknolojinin durdurulamaz ilerleyişi öğretmeyi yeniden şekillendiriyor.",
      fr: "La marche inexorable de la technologie transforme l'enseignement.",
    },
    synonyms: ["relentless", "unstoppable"],
  },
  {
    id: "en-esoteric",
    word: "esoteric",
    pos: "adjective",
    level: "C2",
    category: "school",
    phonetic: "/ˌes.əˈter.ɪk/",
    meaning: { tr: "yalnızca uzmanların anladığı", en: "understood by only a small, specialised group", fr: "ésotérique" },
    example: "Avoid esoteric vocabulary in a beginner's class.",
    exampleT: {
      tr: "Başlangıç seviyesinde çok özel kelimelerden kaçının.",
      fr: "Évitez le vocabulaire ésotérique dans un cours pour débutants.",
    },
    synonyms: ["obscure", "arcane"],
    antonym: "accessible",
  },
  {
    id: "en-garrulous",
    word: "garrulous",
    pos: "adjective",
    level: "C2",
    category: "people",
    phonetic: "/ˈɡær.ə.ləs/",
    meaning: { tr: "geveze", en: "talking a great deal, often about trivial things", fr: "loquace" },
    example: "Our garrulous neighbour kept us on the doorstep.",
    exampleT: {
      tr: "Geveze komşumuz bizi kapı önünde tuttu.",
      fr: "Notre voisin loquace nous a retenus sur le pas de la porte.",
    },
    synonyms: ["talkative", "loquacious"],
    antonym: "taciturn",
  },
  {
    id: "en-propensity",
    word: "propensity",
    pos: "noun",
    level: "C2",
    category: "feelings",
    phonetic: "/prəˈpen.sə.ti/",
    meaning: { tr: "eğilim", en: "a natural tendency to behave in a certain way", fr: "propension" },
    example: "He has a propensity to overthink small errors.",
    exampleT: {
      tr: "Küçük hataları fazla düşünme eğilimi var.",
      fr: "Il a une propension à trop réfléchir aux petites erreurs.",
    },
    synonyms: ["tendency", "inclination"],
    antonym: "aversion",
  },
  {
    id: "en-equivocate",
    word: "equivocate",
    pos: "verb",
    level: "C2",
    category: "work",
    phonetic: "/ɪˈkwɪv.ə.keɪt/",
    meaning: { tr: "kaçamak cevap vermek", en: "to speak vaguely to avoid committing yourself", fr: "tergiverser" },
    example: "Don't equivocate — give a straight answer.",
    exampleT: { tr: "Lafı dolandırma — net bir cevap ver.", fr: "Ne tergiverse pas — donne une réponse claire." },
    synonyms: ["prevaricate", "hedge"],
    antonym: "state plainly",
  },
  {
    id: "en-sagacious",
    word: "sagacious",
    pos: "adjective",
    level: "C2",
    category: "people",
    phonetic: "/səˈɡeɪ.ʃəs/",
    meaning: { tr: "sağgörülü, bilge", en: "showing good judgement and deep understanding", fr: "sagace" },
    example: "Her sagacious advice saved the project.",
    exampleT: { tr: "Sağgörülü tavsiyesi projeyi kurtardı.", fr: "Ses conseils sagaces ont sauvé le projet." },
    synonyms: ["wise", "shrewd"],
    antonym: "foolish",
  },
];
